<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2 setup script
 * Date: Tue, 31 Jul 2012 11:51:36 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['nopassword'] = true;
$cfg['Servers'][$i]['auth_type'] = 'signon';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['SignonSession'] = 'GFrameworkSession';
$cfg['Servers'][$i]['SignonURL'] = 'signon.php';
$cfg['Servers'][$i]['LogoutURL'] = '../index.php?file=logout';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Servers'][$i]['CountTables'] = true;

/* End of servers configuration */

$cfg['MainPageIconic'] = false;
$cfg['ShowCreateDb'] = false;
$cfg['SuggestDBName'] = false;
$cfg['ShowStats'] = false;
$cfg['ShowServerInfo'] = false;
$cfg['ShowChgPassword'] = false;
$cfg['ProtectBinary'] = 0;
$cfg['LightTabs'] = true;
$cfg['UploadDir'] = './tmp/upload/';
$cfg['SaveDir'] = './tmp/download/';
$cfg['blowfish_secret'] = 'sundar12';
$cfg['TitleDefault'] = '@PHPMYADMIN@';
$cfg['TitleTable'] = '@TABLE@ | @PHPMYADMIN@';
$cfg['TitleDatabase'] = '@PHPMYADMIN@';
$cfg['TitleServer'] = '@PHPMYADMIN@';
$cfg['VersionCheck'] = false;
$cfg['ReplaceHelpImg'] = false;
$cfg['MaxDbList'] = 1;
$cfg['PersistentConnections'] = true;
$cfg['SQLQuery']['Validate'] = true;
$cfg['Export']['quick_export_onserver_overwrite'] = true;
$cfg['Export']['compression'] = 'zip';
$cfg['Export']['charset'] = 'utf-8';
$cfg['Export']['onserver_overwrite'] = true;
$cfg['Export']['sql_drop_database'] = true;
$cfg['Export']['sql_drop_table'] = true;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>